export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const ADD_CART_ITEMs = 'ADD_CART_ITEMs';

export const CART_ITEMS_FAILED = 'CART_ITEMS_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';