export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';

export const CARTITEMS_LOADING = 'CARTITEMS_LOADING';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const ADD_CART_ITEMs = 'ADD_CART_ITEMs';
export const CART_EMPTY = 'CART_EMPTY';
export const CART_ITEMS_FAILED = 'CART_ITEMS_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const ORDERS_LOADING = 'ORDERS_LOADING';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';

export const USERS_LOADING = 'USERS_LOADING';
export const FETCH_USERS = 'FETCH_USERS';
export const USERS_FAILED = 'USERS_FAILED';


export const FEEDBACKS_LOADING = 'FEEDBACKS_LOADING';
export const FETCH_FEEDBACKS = 'FETCH_FEEDBACKS';
export const FEEDBACKS_FAILED = 'FEEDBACKS_FAILED';

export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_FAILED = 'GET_COMMENTS_FAILED';